name: concurrency-test
on:
  pull_request:
    types:
      - opened
      - synchronize

concurrency:
  group: ${{ github.workflow }}

jobs:
  testing-concurrency:
    runs-on: ubuntu-latest
    steps:
      - name: say "ready"
        run: echo ready
  ready-for-release:
    runs-on: ubuntu-latest
    steps:
      - name: say "ready"
        run: echo ready
  
  pre-release-checks:
    needs: ready-for-release
    runs-on: ubuntu-latest
    steps:
      - name: say "checked"
        run: echo checked
  ready-for-release2:
    runs-on: ubuntu-latest
    steps:
      - name: say "ready"
        run: echo ready
  pre-release-checks2:
    needs: ready-for-release
    runs-on: ubuntu-latest
    steps:
      - name: say "checked"
        run: echo checked
#tes