name: concurrency-test
on:
  pull_request:
    types:
      - opened
      - synchronize

# concurrency:
#   group: ${{ github.workflow }}

jobs:
  testing-concurrency:
    runs-on: ubuntu-latest
    environment: qa
    steps:
      - name: say "ready"
        run: echo ready
        # triggered by an external API call